### ISSUE TITLE
Hi, cannot use in ts? how should i do?

### ISSUE THREAD

**Issue by seepine** [lxsmnsyc/solid-labels#14]
## log
```
use-count.ts:2  Uncaught ReferenceError: $signal is not defined
    at default (use-count.ts:2:15)
    at _Hot$$App (App.tsx:7:31)
    at @solid-refresh:10:42
    at untrack (chunk-TNBBW3T3.js?v=a09726ce:453:12)
    at Object.fn (@solid-refresh:10:28)
    at runComputation (chunk-TNBBW3T3.js?v=a09726ce:765:22)
    at updateComputation (chunk-TNBBW3T3.js?v=a09726ce:748:3)
    at createMemo (chunk-TNBBW3T3.js?v=a09726ce:258:5)
    at hmrCompWrapper (@solid-refresh:7:20)
    at chunk-TNBBW3T3.js?v=a09726ce:567:12
```

## code
```ts
export default () => {
  let count = $signal(1);
  const countAdd = () => {
    console.log('add', count);
    count++;
  };
  return {
    count,
    countAdd,
  };
};
```

```tsx
import type { Component } from 'solid-js';
import useCount from './use-count';

const App: Component = () => {
  const { count, countAdd } = useCount();

  return (
    <div>
        {count}
        <button onClick={countAdd}>countAdd</button>
    </div>
  );
};
export default App;
```

**Comment by lxsmnsyc** [comment]
did you follow this? https://github.com/lxsmnsyc/solid-labels#typescript

**Comment by lxsmnsyc** [comment]
why do you have it disabled though

**Comment by lxsmnsyc** [comment]
It isn't reactive because of the way you pass `count` to the object. You probably want to use [`$getter`](https://github.com/lxsmnsyc/solid-labels/blob/main/docs/ctf.md#getter)

**Comment by lxsmnsyc** [comment]
which is why I would recommend reading the docs.
